name: Sync from upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync from upstream
        run: |
          git remote add upstream https://github.com/home-assistant/version.git
          git fetch upstream

      - name: Replace image registry
        run: |
          find . -type f -exec sed -i 's|ghcr.io|ghcr.nju.edu.cn|g' {} +

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync file automatically at $(date +'%Y-%m-%d %H:%M:%S')"
          git push

